name: "Trivy PR Scan Reporter"
description: "Comments findings on PRs from Trivy scan results"
author: 'Follow Up Boss'
branding:
  icon: 'shield'
  color: 'orange'
inputs:
  token:
    description: "GitHub token"
    required: true
  scan-type:
    description: "Scan type, either diff or branch"
    required: false
    default: "branch"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    INPUT_SCAN_TYPE: ${{ inputs.scan-type }}
