name: "Trivy PR Scan Reporter"
description: "Comments findings on PRs from Trivy scan results"
author: 'Follow Up Boss'
branding:
  icon: 'shield'
  color: 'orange'
inputs:
  token:
    description: "GitHub token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
